name: vocalize
channels:
  - conda-forge
  - defaults
dependencies:
  - atk=2.25.90
  - attrs=18.2.0
  - audioread=2.1.6
  - backcall=0.1.0
  - blas=1.1
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - cairo=1.16.0
  - certifi=2018.11.29
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.2
  - entrypoints=0.3
  - expat=2.2.5
  - ffmpeg=4.1
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gdk-pixbuf=2.36.12
  - gettext=0.19.8.1
  - glib=2.58.2
  - gmp=6.1.2
  - gnutls=3.6.5
  - gobject-introspection=1.58.2
  - graphite2=1.3.13
  - gstreamer=1.14.4
  - gtk2=2.24.31
  - harfbuzz=2.3.1
  - icu=58.2
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=3.0.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - librosa=0.6.3
  - libsodium=1.0.16
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - llvmlite=0.26.0
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - mistune=0.8.4
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.4.1
  - notebook=5.7.4
  - numba=0.41.0
  - numpy=1.16.1
  - openblas=0.3.3
  - openh264=1.8.0
  - openssl=1.0.2q
  - pandoc=2.6
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.3.4
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - pixman=0.34.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - python=3.7.1
  - python-dateutil=2.8.0
  - pyzmq=18.0.0
  - qt=5.6.2
  - qtconsole=4.4.3
  - readline=7.0
  - resampy=0.2.1
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - x264=1!152.20180717
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - future==0.17.1
    - mir-eval==0.5
    - sklearn==0.0
    - vamp==1.1.0

